### ISSUE TITLE
Unexpected keys in pretrained weight

### ISSUE THREAD

**Issue by MrZilinXiao** [zengqunzhao/Former-DFER#1]
Thanks for your impressive works!
However, I noticed that there are some unexcepted keys in the pretrained weight you provide. Setting `strict=False` will do the trick and load_status shows no missing keys. Still, I am wondering if it matters, or you just upload a weight mixing with old parameters. 

Unexpected key List: 
```
unexpected_keys: ['s_former.spatial_transformer.layers.1.0.fn.norm.weight', 's_former.spatial_transformer.layers.1.0.fn.norm.bias', 's_former.spatial_transformer.layers.1.0.fn.fn.to_qkv.weight', 's_former.spatial_transformer.layers.1.0.fn.fn.to_out.0.weight', 's_former.spatial_transformer.layers.1.0.fn.fn.to_out.0.bias', 's_former.spatial_transformer.layers.1.1.fn.norm.weight', 's_former.spatial_transformer.layers.1.1.fn.norm.bias', 's_former.spatial_transformer.layers.1.1.fn.fn.net.0.weight', 's_former.spatial_transformer.layers.1.1.fn.fn.net.0.bias', 's_former.spatial_transformer.layers.1.1.fn.fn.net.3.weight', 's_former.spatial_transformer.layers.1.1.fn.fn.net.3.bias', 's_former.spatial_transformer.layers.2.0.fn.norm.weight', 's_former.spatial_transformer.layers.2.0.fn.norm.bias', 's_former.spatial_transformer.layers.2.0.fn.fn.to_qkv.weight', 's_former.spatial_transformer.layers.2.0.fn.fn.to_out.0.weight', 's_former.spatial_transformer.layers.2.0.fn.fn.to_out.0.bias', 's_former.spatial_transformer.layers.2.1.fn.norm.weight', 's_former.spatial_transformer.layers.2.1.fn.norm.bias', 's_former.spatial_transformer.layers.2.1.fn.fn.net.0.weight', 's_former.spatial_transformer.layers.2.1.fn.fn.net.0.bias', 's_former.spatial_transformer.layers.2.1.fn.fn.net.3.weight', 's_former.spatial_transformer.layers.2.1.fn.fn.net.3.bias']
```

**Comment by zengqunzhao** [comment]
> Thanks for your impressive works! However, I noticed that there are some unexcepted keys in the pretrained weight you provide. Setting `strict=False` will do the trick and load_status shows no missing keys. Still, I am wondering if it matters, or you just upload a weight mixing with old parameters.
> 
> Unexpected key List:
> 
> ```
> unexpected_keys: ['s_former.spatial_transformer.layers.1.0.fn.norm.weight', 's_former.spatial_transformer.layers.1.0.fn.norm.bias', 's_former.spatial_transformer.layers.1.0.fn.fn.to_qkv.weight', 's_former.spatial_transformer.layers.1.0.fn.fn.to_out.0.weight', 's_former.spatial_transformer.layers.1.0.fn.fn.to_out.0.bias', 's_former.spatial_transformer.layers.1.1.fn.norm.weight', 's_former.spatial_transformer.layers.1.1.fn.norm.bias', 's_former.spatial_transformer.layers.1.1.fn.fn.net.0.weight', 's_former.spatial_transformer.layers.1.1.fn.fn.net.0.bias', 's_former.spatial_transformer.layers.1.1.fn.fn.net.3.weight', 's_former.spatial_transformer.layers.1.1.fn.fn.net.3.bias', 's_former.spatial_transformer.layers.2.0.fn.norm.weight', 's_former.spatial_transformer.layers.2.0.fn.norm.bias', 's_former.spatial_transformer.layers.2.0.fn.fn.to_qkv.weight', 's_former.spatial_transformer.layers.2.0.fn.fn.to_out.0.weight', 's_former.spatial_transformer.layers.2.0.fn.fn.to_out.0.bias', 's_former.spatial_transformer.layers.2.1.fn.norm.weight', 's_former.spatial_transformer.layers.2.1.fn.norm.bias', 's_former.spatial_transformer.layers.2.1.fn.fn.net.0.weight', 's_former.spatial_transformer.layers.2.1.fn.fn.net.0.bias', 's_former.spatial_transformer.layers.2.1.fn.fn.net.3.weight', 's_former.spatial_transformer.layers.2.1.fn.fn.net.3.bias']
> ```

Thanks for your interest.
Sorry, I did not verify the pre-trained model. Maybe it does not match the current code, I will update it later.

**Comment by CeLuigi** [comment]
Hi! Any update about this issue?

**Comment by zengqunzhao** [comment]
> Hi! Any update about this issue?

Hi, sorry for the delay. I have updated the code and pre-train models.
