### ISSUE TITLE
可以简单解释一下什么是“Dynamic Sampling”吗？文章中这一策略明显提升了性能，是分段采样视频帧？望回复，谢谢。

### ISSUE THREAD

**Issue by wyynevergiveup** [zengqunzhao/Former-DFER#2]

**Comment by zengqunzhao** [comment]
> _No description provided._

你好，具体做法文章中有写，只说下训练阶段，先将视频的所有帧分为N段，然后从每段里面随机挑选M帧，最后的视频帧数为N*M帧。这样做其实是将视频中所有帧都用到了训练中，提高了训练数据的充分性，同时，随机挑选也提高了训练数据的多样性。
