### ISSUE TITLE
Inquiry about Pre-training of ResNet18 Used in Your Paper

### ISSUE THREAD

**Issue by cyinen** [zengqunzhao/Former-DFER#5]
Hello,

I recently read your paper and am interested in the implementation details of the ResNet18 model you used. Could you please clarify if the ResNet18 model employed in your research was pre-trained on the MS-Celeb-1M dataset? Understanding this detail is crucial for replicating your results and furthering my research.

Thank you for your time and contribution to the field.

**Comment by zengqunzhao** [comment]
> Hello,
> 
> I recently read your paper and am interested in the implementation details of the ResNet18 model you used. Could you please clarify if the ResNet18 model employed in your research was pre-trained on the MS-Celeb-1M dataset? Understanding this detail is crucial for replicating your results and furthering my research.
> 
> Thank you for your time and contribution to the field.

Hi, Thanks for your attention.

The whole model was trained from scratch on DFEW. But for AFEW, consistent with the previous work, we first pre-train our model on DFEW (fd1) and then fine-turn on AFEW (more details please find in paper). Hope this helps.
